Repository BinaryStudioAcademy/bsa-winter21-22-codi, pull requests merged in 2022-02, with the labels that each got.

#6 Added-BootStrap
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/polyfills.ts
  frontend/src/styles/index.sass
Labels: enhancement

#8 Create codi-http-client
  frontend/src/app/core/services/codi-http-client.service.ts
Labels: enhancement

#9 Add database diagram
  docs/codi_database_structure.png
Labels: documentation

#10 Add login/register components
  frontend/src/app/app-routing.module.ts
  frontend/src/app/modules/auth/auth-routing.module.ts
  frontend/src/app/modules/auth/auth.module.ts
  frontend/src/app/modules/auth/login/login.component.html
  frontend/src/app/modules/auth/login/login.component.sass
  frontend/src/app/modules/auth/login/login.component.ts
  frontend/src/app/modules/auth/register/register.component.html
  frontend/src/app/modules/auth/register/register.component.sass
  frontend/src/app/modules/auth/register/register.component.ts
  frontend/src/app/modules/auth/shared/custom-validators.ts
  frontend/src/assets/images/github.png
  frontend/src/assets/images/google.png
  frontend/src/assets/images/warning.png
  frontend/src/styles/variables.sass
Labels: enhancement

#15 Add toastr notifications service
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/core/services/notification.service.ts
  frontend/src/app/modules/auth/login/login.component.html
  frontend/src/app/modules/auth/login/login.component.ts
  frontend/src/styles/index.sass
Labels: enhancement

#20 Fix toastr behavior
  frontend/src/app/app.module.ts
Labels: bug

#19 Add confirmation dialog
  frontend/src/app/core/models/confirmation-dialog/confirmation-dialog-options.ts
  frontend/src/app/core/models/confirmation-dialog/confirmation-dialog-result.ts
  frontend/src/app/core/services/confirmation-dialog.service.ts
  frontend/src/app/modules/auth/login/login.component.html
  frontend/src/app/modules/auth/login/login.component.ts
  frontend/src/app/shared/components/confirmation-dialog/confirmation-dialog.component.html
  frontend/src/app/shared/components/confirmation-dialog/confirmation-dialog.component.sass
  frontend/src/app/shared/components/confirmation-dialog/confirmation-dialog.component.ts
  frontend/src/app/shared/shared.module.ts
  frontend/src/styles/global.sass
Labels: enhancement

#24 Fix iframe reload
  frontend/src/app/core/services/confirmation-dialog.service.ts
  frontend/src/app/shared/components/confirmation-dialog/confirmation-dialog.component.html
  frontend/src/app/shared/components/confirmation-dialog/confirmation-dialog.component.ts
  frontend/src/styles/global.sass
Labels: bug

#23 Feature/rabbit mq wrapper
  backend/Codi.All.sln
  backend/Codi.Core/Codi.Core.BLL/Codi.Core.BLL.csproj
  backend/Codi.Core/Codi.Core.BLL/Interfaces/IMessageService.cs
  backend/Codi.Core/Codi.Core.BLL/RabbitMQ/MessageService.cs
  backend/Codi.Core/Codi.Core.WebAPI/Controllers/SampleController.cs
  backend/Codi.Core/Codi.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  backend/Codi.Core/Codi.Core.WebAPI/Program.cs
  backend/Codi.Core/Codi.Core.WebAPI/appsettings.json
  backend/Codi.RabbitMQ/Codi.RabbitMQ.csproj
  backend/Codi.RabbitMQ/Interfaces/IMessageConsumer.cs
  backend/Codi.RabbitMQ/Interfaces/IMessageConsumerScope.cs
  backend/Codi.RabbitMQ/Interfaces/IMessageConsumerScopeFactory.cs
  backend/Codi.RabbitMQ/Interfaces/IMessageProducer.cs
  backend/Codi.RabbitMQ/Interfaces/IMessageProducerScope.cs
  backend/Codi.RabbitMQ/Interfaces/IMessageProducerScopeFactory.cs
  backend/Codi.RabbitMQ/Interfaces/IMessageQueue.cs
  backend/Codi.RabbitMQ/Models/MessageConsumerSettings.cs
  backend/Codi.RabbitMQ/Models/MessageProducerSettings.cs
  backend/Codi.RabbitMQ/Models/MessageScopeSettings.cs
  backend/Codi.RabbitMQ/Services/MessageConsumer.cs
  backend/Codi.RabbitMQ/Services/MessageConsumerScope.cs
  backend/Codi.RabbitMQ/Services/MessageConsumerScopeFactory.cs
  backend/Codi.RabbitMQ/Services/MessageProducer.cs
  backend/Codi.RabbitMQ/Services/MessageProducerScope.cs
  backend/Codi.RabbitMQ/Services/MessageProducerScopeFactory.cs
  backend/Codi.RabbitMQ/Services/MessageQueue.cs
Labels: enhancement

#26 Update email validation
  frontend/src/app/modules/auth/register/register.component.html
  frontend/src/app/modules/auth/register/register.component.ts
  frontend/src/app/shared/constants/regexs.ts
Labels: enhancement

#28 Fix "Home page" bugs
  frontend/angular.json
  frontend/src/app/modules/main/create-button/create-button.component.sass
  frontend/src/app/modules/main/header/header.component.html
  frontend/src/app/modules/main/header/header.component.sass
  frontend/src/app/modules/main/header/side-nav-toggler/side-nav-toggler.component.html
  frontend/src/app/modules/main/header/side-nav-toggler/side-nav-toggler.component.sass
  frontend/src/app/modules/main/header/side-nav/side-nav.component.html
  frontend/src/app/modules/main/header/side-nav/side-nav.component.sass
  frontend/src/app/modules/main/header/top-nav/top-nav.component.html
  frontend/src/app/modules/main/header/top-nav/top-nav.component.sass
  frontend/src/app/modules/main/home-page/home-page.component.sass
  frontend/src/app/modules/main/main.module.ts
Labels: bug

#31 Fix confirmation dialog close button clickable area
  frontend/src/styles/global.sass
Labels: bug

#22 Page layout created
  frontend/src/app/modules/landing/landing-content/landing-content.component.html
  frontend/src/app/modules/landing/landing-content/landing-content.component.sass
  frontend/src/app/modules/landing/landing-content/landing-content.component.ts
  frontend/src/app/modules/landing/landing-footer/landing-footer.component.html
  frontend/src/app/modules/landing/landing-footer/landing-footer.component.sass
  frontend/src/app/modules/landing/landing-footer/landing-footer.component.ts
  frontend/src/app/modules/landing/landing-header/landing-header.component.html
  frontend/src/app/modules/landing/landing-header/landing-header.component.sass
  frontend/src/app/modules/landing/landing-header/landing-header.component.ts
  frontend/src/app/modules/landing/landing-page/landing-page.component.html
  frontend/src/app/modules/landing/landing-page/landing-page.component.sass
  frontend/src/app/modules/landing/landing.module.ts
  frontend/src/assets/images/landinglogo.jpg
Labels: enhancement

#18 Add firebase, Jwt , AuthService, Google provider
  backend/Codi.Core/Codi.Core.WebAPI/Codi.Core.WebAPI.csproj
  backend/Codi.Core/Codi.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  backend/Codi.Core/Codi.Core.WebAPI/Program.cs
  backend/Codi.Core/Codi.Core.WebAPI/appsettings.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/core/core.module.ts
  frontend/src/app/core/interceptors/jwt.interceptor.ts
  frontend/src/app/core/services/auth.service.ts
  frontend/src/app/modules/auth/auth.module.ts
  frontend/src/app/modules/auth/login/login.component.html
  frontend/src/app/modules/auth/login/login.component.ts
  frontend/src/app/modules/auth/register/register.component.html
  frontend/src/app/modules/auth/register/register.component.ts
  frontend/src/environments/environment.prod.ts
  frontend/src/environments/environment.ts
  frontend/tsconfig.json
  package-lock.json
Labels: help wanted

#33 Add "Not Found Page"
  frontend/src/app/app-routing.module.ts
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/shared/components/not-found/not-found.component.html
  frontend/src/app/shared/components/not-found/not-found.component.sass
  frontend/src/assets/images/404.png
Labels: enhancement

#30 Add MongoDB
  backend/Codi.Core/Codi.Core.Common/Enums/FSNodeType.cs
  backend/Codi.Core/Codi.Core.DAL/Codi.Core.DAL.csproj
  backend/Codi.Core/Codi.Core.DAL/ConfigurationExtensions.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Attributes/BsonCollectionAttribute.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Context/Abstract/IMongoContext.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Context/CodiFileStorageContext.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Entities/Abstract/Document.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Entities/Abstract/IDocument.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Entities/FSNode.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Entities/File.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Entities/Template.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Repositories/Abstract/BaseMongoRepository.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Repositories/Abstract/IFileRepository.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Repositories/Abstract/IMongoRepository.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Repositories/Abstract/ITemplateRepository.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Repositories/FileRepository.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Repositories/TemplateRepository.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Seed/CodiFileStorageSeed.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Seed/TemplatesSeed.cs
  backend/Codi.Core/Codi.Core.DAL/NoSql/Settings/CodiFileStorageSettings.cs
  backend/Codi.Core/Codi.Core.WebAPI/Extentions/ApplicationBuilderExtensions.cs
  backend/Codi.Core/Codi.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  backend/Codi.Core/Codi.Core.WebAPI/Program.cs
  backend/Codi.Core/Codi.Core.WebAPI/appsettings.json
  docker-compose.services.yml
Labels: enhancement

#36 Update migration flow
  backend/Codi.Core/Codi.Core.WebAPI/Program.cs
Labels: bug

#40 Bugfix "Add not found page"
  frontend/src/app/shared/components/not-found/not-found.component.html
  frontend/src/app/shared/components/not-found/not-found.component.sass
  frontend/src/assets/images/404.png
  frontend/src/assets/images/404.svg
Labels: bug

#42 Feature/38 add monaco editor
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/modules/main/main.module.ts
Labels: enhancement

#41 Fixed bug
  frontend/src/app/modules/landing/landing-footer/landing-footer.component.sass
  frontend/src/app/modules/landing/landing-page/landing-page.component.html
  frontend/src/app/modules/landing/landing-page/landing-page.component.sass
Labels: enhancement

#43 Create app page
  frontend/src/app/modules/auth/login/login.component.html
  frontend/src/app/modules/auth/login/login.component.sass
  frontend/src/app/modules/auth/register/register.component.html
  frontend/src/app/modules/auth/register/register.component.sass
  frontend/src/app/modules/landing/landing-content/landing-content.component.sass
  frontend/src/app/modules/landing/landing-footer/landing-footer.component.sass
  frontend/src/app/modules/landing/landing-header/landing-header.component.html
  frontend/src/app/modules/landing/landing-header/landing-header.component.sass
  frontend/src/app/modules/landing/landing-page/landing-page.component.sass
  frontend/src/app/modules/main/applications/applicaions.component.html
  frontend/src/app/modules/main/applications/applicaions.component.sass
  frontend/src/app/modules/main/applications/applicaions.component.ts
  frontend/src/app/modules/main/applications/publish-app-dialog/publish-app-dialog.component.html
  frontend/src/app/modules/main/applications/publish-app-dialog/publish-app-dialog.component.sass
  frontend/src/app/modules/main/applications/publish-app-dialog/publish-app-dialog.component.ts
  frontend/src/app/modules/main/create-button/create-button.component.html
  frontend/src/app/modules/main/create-button/create-button.component.sass
  frontend/src/app/modules/main/create-button/create-button.component.ts
  frontend/src/app/modules/main/create-button/side-nav-create-button/side-nav-create-button.component.html
  frontend/src/app/modules/main/create-button/side-nav-create-button/side-nav-create-button.component.sass
  frontend/src/app/modules/main/create-button/side-nav-create-button/side-nav-create-button.component.ts
  frontend/src/app/modules/main/header/header.component.html
  frontend/src/app/modules/main/header/header.component.sass
  frontend/src/app/modules/main/header/side-nav-toggler/side-nav-toggler.component.sass
  frontend/src/app/modules/main/header/side-nav/side-nav.component.html
  frontend/src/app/modules/main/header/side-nav/side-nav.component.sass
  frontend/src/app/modules/main/header/top-nav/top-nav.component.html
  frontend/src/app/modules/main/header/top-nav/top-nav.component.sass
  frontend/src/app/modules/main/header/top-nav/top-nav.component.ts
  frontend/src/app/modules/main/home-page/home-page.component.html
  frontend/src/app/modules/main/home-page/home-page.component.sass
  frontend/src/app/modules/main/main-page/main-page.component.html
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/shared/components/not-found/not-found.component.sass
  frontend/src/assets/images/github_white.png
  frontend/src/styles/auth-pages.sass
  frontend/src/styles/global.sass
  frontend/src/styles/index.sass
  frontend/src/styles/variables.sass
Labels: enhancement

#46 Bug fix cursor is a pointer
  frontend/src/app/modules/main/home-page/home-page.component.sass
  frontend/src/styles/global.sass
Labels: bug

#49 Fix app cards layout
  frontend/src/app/core/services/side-nav.service.ts
  frontend/src/app/modules/main/applications/applicaions.component.sass
  frontend/src/app/modules/main/courses-page/courses-page.component.html
  frontend/src/app/modules/main/courses-page/courses-page.component.sass
  frontend/src/app/modules/main/header/header.component.html
  frontend/src/app/modules/main/header/side-nav/side-nav.component.html
  frontend/src/app/modules/main/header/side-nav/side-nav.component.sass
  frontend/src/app/modules/main/header/side-nav/side-nav.component.ts
  frontend/src/app/modules/main/header/top-nav/top-nav.component.html
  frontend/src/app/modules/main/header/top-nav/top-nav.component.sass
  frontend/src/app/modules/main/home-page/home-page.component.sass
  frontend/src/app/modules/main/myprojects-page/myprojects-page.component.html
  frontend/src/app/modules/main/myprojects-page/myprojects-page.component.sass
Labels: bug

#51 Fixed sidenav only on small screens
  frontend/src/app/modules/main/header/header.component.html
  frontend/src/app/modules/main/header/side-nav/side-nav.component.sass
Labels: bug

#53 Update landing-page.component.sass
  frontend/src/app/modules/landing/landing-page/landing-page.component.sass
Labels: bug

#61 fix users route
  backend/Codi.Core/Codi.Core.WebAPI/Controllers/UsersController.cs
  frontend/src/app/core/services/user.service.ts
Labels: bug
